agent:
  system_template: |
    You are a helpful assistant that can interact with a computer.

  instance_template: |
    Please solve this issue: {{problem_statement}}

    You can execute bash commands and edit files to implement the necessary changes.
    <IMPORTANT>
    1. Every response must contain exactly one action
    2. The action must be enclosed in triple backticks
    3. You cannot change directories or set new environment variables
    4. To finish, issue the following command: `echo MICRO_SWE_AGENT_FINAL_OUTPUT`.
       Do not combine it with any other command.
    </IMPORTANT>

  step_limit: 0.
  cost_limit: 0.
  confirm_actions: true
environment:
  env:
    PAGER: cat
    MANPAGER: cat
    LESS: -R
    PIP_PROGRESS_BAR: 'off'
    TQDM_DISABLE: '1'